shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("webapp.urls")),
    path('accounts/', include("accounts.urls")),
    path('v3/', include('api_v3.urls'))
]

webapp/urls.py
from django.urls import path

from webapp.views import IndexView, ProductView, ProductCreateView, ProductUpdateView, ProductDeleteView, CartAddView, \
    CartView, CartDeleteView, CartDeleteOneView, OrderCreate

app_name = "webapp"

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('product/<int:pk>/', ProductView.as_view(), name='product_view'),
    path('products/add/', ProductCreateView.as_view(), name='product_create'),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('product/<int:pk>/add-to-cart/', CartAddView.as_view(), name='add_to_cart'),
    path('cart/', CartView.as_view(), name='cart'),
    path('cart/<int:pk>/delete/', CartDeleteView.as_view(), name='remove_for_cart'),
    path('cart/<int:pk>/one-delete/', CartDeleteOneView.as_view(), name='remove_one_for_cart'),
    path('order/create/', OrderCreate.as_view(), name='order_create')
]

webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.core.validators import MinValueValidator
from django.db.models import Sum, F

DEFAULT_CATEGORY = 'other'
CATEGORY_CHOICES = (
    (DEFAULT_CATEGORY, 'Разное'),
    ('food', 'Еда'),
    ('tech', 'Бытовая техника'),
    ('tools', 'Инструменты'),
    ('toys', 'Игрушки'),
)


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    description = models.TextField(max_length=2000, null=True, blank=True, verbose_name='Описание')
    category = models.CharField(max_length=20, default=DEFAULT_CATEGORY, choices=CATEGORY_CHOICES,
                                verbose_name='Категория')
    amount = models.PositiveIntegerField(verbose_name='Остаток')
    price = models.DecimalField(verbose_name='Цена', max_digits=7, decimal_places=2,
                                validators=(MinValueValidator(0),))

    def __str__(self):
        return f'{self.name} - {self.amount}'

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class Order(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='orders', verbose_name='Human', null=True, blank=True)
    name = models.CharField(max_length=50, verbose_name='Имя')
    phone = models.CharField(max_length=30, verbose_name='Телефон')
    address = models.CharField(max_length=100, verbose_name='Адрес')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    products = models.ManyToManyField('webapp.Product', related_name='orders', verbose_name='Товары',
                                      through='webapp.OrderProduct', through_fields=['order', 'product'])

    def __str__(self):
        return f'{self.name} - {self.phone}'

    def get_total(self):
        total = self.order_products.aggregate(total=Sum(F("qty") * F("product__price")))
        return total["total"]

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'


class OrderProduct(models.Model):
    product = models.ForeignKey('webapp.Product', on_delete=models.CASCADE,
                                verbose_name='Товар', related_name='order_products')
    order = models.ForeignKey('webapp.Order', on_delete=models.CASCADE,
                              verbose_name='Заказ', related_name='order_products')
    qty = models.PositiveIntegerField(verbose_name='Количество')

    def __str__(self):
        return f'{self.product.name} - {self.order.name}'

    def get_sum(self):
        return self.qty * self.product.price

    class Meta:
        verbose_name = 'Товар в заказе'
        verbose_name_plural = 'Товары в заказе'

webapp/forms.py
from django import forms
from webapp.models import Product, Order


class SearchForm(forms.Form):
    search = forms.CharField(max_length=50, required=False, label='Найти')


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = []


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["name", "phone", "address"]

webapp/views/base_view.py
from django.db.models import Q
from django.utils.http import urlencode
from django.views.generic import ListView

from webapp.forms import SearchForm


class SearchView(ListView):
    search_form_class = SearchForm
    search_form_field = "search"
    query_name = "query"
    search_fields = []

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        if self.search_value:
            return self.model.objects.filter(self.get_query())
        return self.model.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["form"] = self.form
        if self.search_value:
            query = urlencode({self.search_form_field: self.search_value})
            context[self.query_name] = query
            context[self.search_form_field] = self.search_value
        return context

    def get_search_form(self):
        return self.search_form_class(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data.get(self.search_form_field)

    def get_query(self):
        query = Q()
        for field in self.search_fields:
            kwargs = {field: self.search_value}
            query = query | Q(**kwargs)
        return query

webapp/views/cart.py
from django.db.models import F
from django.http import HttpResponseRedirect, HttpResponseBadRequest
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import CreateView, ListView, DeleteView, TemplateView

from webapp.forms import OrderForm, ProductForm
from webapp.models import Product, Order, OrderProduct


class CartAddView(View):

    def post(self, request, pk, *args, **kwargs):
        product = get_object_or_404(Product, pk=pk)
        qty = int(self.request.POST.get("qty"))
        if qty > product.amount:
            return HttpResponseBadRequest(
                f"Количество товара {product.name} всего {product.amount}. Добавить {qty} штук не получится")
        else:
            cart = self.request.session.get("cart", {})
            if str(product.pk) in cart:
                cart[str(product.pk)] += qty
            else:
                cart[str(product.pk)] = qty
            self.request.session['cart'] = cart
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        next = self.request.GET.get("next")
        if next:
            return next
        return reverse("webapp:index")


class CartView(TemplateView):
    template_name = "cart/cart_view.html"
    context_object_name = "cart"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart = self.request.session.get('cart', {})
        products = []
        total = 0
        for pk, qty in cart.items():
            product = Product.objects.get(pk=pk)
            product_total = qty * product.price
            total += product_total
            products.append({"product": product, "qty": qty, 'product_total': product_total})
        #products = Product.objects.filter(id__in=cart.keys()).annotate(total=F('price') * cart.get(F("pk")))
        print(products)
        context['cart'] = products
        context['total'] = total
        context['form'] = OrderForm()
        return context


class CartDeleteView(View):
    def get(self, request, pk, *args, **kwargs):
        cart = self.request.session.get('cart', {})
        if str(pk) in cart:
            cart.pop(str(pk))
            self.request.session['cart'] = cart

        return redirect("webapp:cart")


class CartDeleteOneView(View):

    def get(self, request, pk, *args, **kwargs):
        cart = self.request.session.get('cart', {})
        if str(pk) in cart:
            cart[str(pk)] -= 1
            if cart[str(pk)] < 1:
                cart.pop(str(pk))
            self.request.session['cart'] = cart
        return redirect("webapp:cart")



class OrderCreate(CreateView):
    model = Order
    form_class = OrderForm
    success_url = reverse_lazy('webapp:index')

    # def form_valid(self, form):
    #     order = form.save()
    #     for item in Cart.objects.all():
    #         OrderProduct.objects.create(product=item.product, qty=item.qty, order=order)
    #         item.product.amount -= item.qty
    #         item.product.save()
    #         item.delete()
    #
    #     return HttpResponseRedirect(self.success_url)

    def form_valid(self, form):
        order = form.save(commit=False)
        if self.request.user.is_authenticated:
            order.user = self.request.user
        order.save()
        products = []
        order_products = []
        cart = self.request.session.get('cart', {})
        if cart:
            for pk, qty in cart.items():
                product = Product.objects.get(pk=pk)
                order_products.append(OrderProduct(product=product, qty=qty, order=order))
                product.amount -= qty
                products.append(product)
            OrderProduct.objects.bulk_create(order_products)
            Product.objects.bulk_update(products, ("amount",))
            self.request.session.pop('cart')
        return HttpResponseRedirect(self.success_url)

webapp/views/products.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import UpdateView, DeleteView, DetailView, CreateView

from webapp.forms import ProductForm
from webapp.models import Product
from webapp.views.base_view import SearchView


class IndexView(SearchView):
    model = Product
    template_name = 'product/index.html'
    ordering = ['category', 'name']
    search_fields = ['name__icontains']
    paginate_by = 6
    context_object_name = 'products'

    def get_queryset(self):
        return super().get_queryset().filter(amount__gt=0)


class ProductView(DetailView):
    model = Product
    template_name = 'product/product_view.html'
    queryset = Product.objects.filter(amount__gt=0)


class ProductCreateView(PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'product/product_create.html'
    permission_required = "webapp.add_product"

    def has_permission(self):
        return super().has_permission() or self.request.user.is_superuser

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.pk})


class ProductUpdateView(PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'product/product_update.html'
    permission_required = "webapp.change_product"

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.pk})


class ProductDeleteView(PermissionRequiredMixin, DeleteView):
    model = Product
    template_name = 'product/product_delete.html'
    success_url = reverse_lazy('webapp:index')
    permission_required = "webapp.delete_product"

webapp/templates/product/index.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-center">Товары</h1>
    <div class="my-3">{% include 'partial/search.html' %}</div>
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
    <div class="row my-3">
        {% for product in products %}
            <div class="col-12 col-md-4 col-lg-4">
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title"><a
                                href="{% url "webapp:product_view" product.pk %}">{{ product.name }}</a></h5>
                        <p class="card-text">Категория: {{ product.get_category_display }}</p>
                        <p class="card-text">Осталось: {{ product.amount }} по {{ product.price }} сом</p>
                        {% if user.is_superuser or perms.webapp.change_product or perms.webapp.delete_product %}
                        <div class="btn-group">
                            <a class="btn btn-primary" href="{% url 'webapp:product_update' product.pk %}">Изменить</a>
                            <a class="btn btn-danger" href="{% url 'webapp:product_delete' product.pk %}">Удалить</a>
                        </div>
                        {% endif %}
                        {% include "partial/cart_add_form.html" %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}

webapp/templates/product/product_create.html
{% extends 'base.html' %}

{% block title %}Создание{% endblock %}

{% block content %}
    <h1>Создать товар</h1>
    <form method="post">
        {% include 'partial/form.html' with button_text="Создать" %}
    </form>

{% endblock %}

webapp/templates/product/product_delete.html
{% extends 'base.html' %}

{% block title %}Удаление{% endblock %}

{% block nav %}
    <li class="nav-item"><a class="nav-link" href="{% url 'webapp:product_view' product.pk %}">Отмена</a></li>
{% endblock %}

{% block content %}
    <h1>Вы уверены, что хотите удалить товар "{{ product.name }}" ({{ product.get_category_display }})?</h1>
    <form action="{% url "webapp:product_delete" product.pk %}" method="post">
        {% csrf_token %}
        <div class="btn-group">
            <button class="btn btn-danger" type="submit">Да</button>
            <a class="btn btn-primary" href="{% url 'webapp:product_view' product.pk %}">Отмена</a>
        </div>
    </form>
{% endblock %}

webapp/templates/product/product_update.html
{% extends 'base.html' %}

{% block title %}Изменение{% endblock %}

{% block content %}
    <h1>Изменить товар</h1>
    <form method="post">
        {% include 'partial/form.html' with button_text="Изменить" %}
    </form>
{% endblock %}

webapp/templates/product/product_view.html
{% extends 'base.html' %}

{% block title %}Просмотр{% endblock %}


{% block nav %}
    {% if user.is_superuser or perms.webapp.change_product or perms.webapp.delete_product %}
    <li class="nav-item"><a class="nav-link" href="{% url 'webapp:product_update' product.pk %}">Изменить</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'webapp:product_delete' product.pk %}">Удалить</a></li>
{% endif %}
{% endblock %}


{% block content %}
    <div class="card">
        <div class="card-body">
            <h1>{{ product.name }}</h1>
            <p class="card-text">Категория: {{ product.get_category_display }}</p>
            <p class="card-text">Осталось: {{ product.amount }} по {{ product.price }} сом</p>
            <p class="pre">{{ product.description }}</p>
        </div>
    </div>
    {% include "partial/cart_add_form.html" %}
{% endblock %}